### ISSUE TITLE
iterating iso metadata?

### ISSUE THREAD

**Issue by dougstarfish** [barneygale/isoparser#19]
I can see you have all of the iso metadata in there, which is exactly what I'm after. I can't find a built-in method/mechanism for extracting it. While it's possible to iterate over an iso object using something like iso.volume_descriptors['primary'].__dict__.items(), I wonder if you have a more direct, supported, object method rather than digging into the private __dict__ membership directly?

**Comment by dougstarfish** [comment]
I'll could use vars(iso.volume_descriptors['primary']) but a 'header()' method to pull all of them in one swoop would be pretty useful as a generalized mechanism. What do you think?

something like

class PrimaryVD ...
  ...
  def header(self):
    return self.__dict__.items()

and you could call it like 

for k, v in iso.volume_descriptors['primary'].header():
  print(k + ' = ' + str(v))

**Comment by barneygale** [comment]
This is a deliberate decision as the underlying data is a kind of struct rather than a mapping. Elsewhere in the library we use object attributes for storing data that's specific to that class of object. To me, a dict is the wrong abstraction for VD entries given its set of keys is pre-defined.  For your use case I think `vars()` should do the trick. Hope this sounds reasonable!
